[[entity]]
name = "player"
transform = { position = [0.5, 0.5] }
mesh = { shape = "square", color = [0.0, 1.0, 0.0] }
script = { file = "player.lua", speed = 1.5 }

[[entity]]
name = "rock"
transform = { position = [-0.5, -0.5] }
mesh = { shape = "triangle", color = [1.0, 0.4, 0.8] }
